### ISSUE TITLE
`pip install git+https://github.com/LLNL/fudge.git@6.6.0` fails due to missing 6.6.0 tag

### ISSUE THREAD

**Issue by thomasms** [LLNL/fudge#12]
Hi,

I am having trouble installing the latest version 6.6.0 via the following command:

```bash
pip install git+https://github.com/LLNL/fudge.git@6.6.0
```

See the error below.
![image](https://github.com/LLNL/fudge/assets/8820266/382f3e71-367a-4475-b009-e2ae24f09bcd)

I *think* - but of course I could very well be mistaken - that because there is no 6.6.0 tag on GitHub.

In order to get 6.6.0 installed I instead did:

```bash
pip install git+https://github.com/LLNL/fudge.git@master
```

With

```python
import fudge
print(fudge.__version__)
```
giving `6.6`.
![image](https://github.com/LLNL/fudge/assets/8820266/fce3201a-366b-4378-bb24-53fece1a9492)

Am I doing something wrong here?

**Comment by mattooca** [comment]
Thanks for reporting that,  I forgot to push the tag.  Should be fixed now.
