### ISSUE TITLE
setup.py Appends Non-existent Directories to Numpy Path

### ISSUE THREAD

**Issue by watsot2** [LLNL/fudge#13]
When attempting to install fudge v6.6.0 via pip after creating a virtual environment using conda as described in the instructions, I get the following error messages:

Requirement already satisfied: numpy in /opt/miniconda3/envs/fudge/lib/python3.9/site-packages (from fudge==6.6) (2.0.1)
Building wheels for collected packages: fudge, brownies, crossSectionAdjustForHeatedTarget, numericalFunctions, PoPs, pqu, xData
  Building wheel for fudge (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [316 lines of output]
      running bdist_wheel
.
.
.
        File "/tmp/pip-req-build-k3et294c/setup.py", line 50, in run
          assert os.path.isdir(numpyPath), 'Numpy path "%s" NOT FOUND' % numpyPath
      AssertionError: Numpy path "/opt/miniconda3/envs/fudge/lib/python3.9/site-packages/numpy/core/include/numpy" NOT FOUND
      [end of output]

Numpy was successfully installed in the conda environment when created, but the "include/" directory and "numpy" file do not exist in the installation directory for the environment.  Is this a difference between supported versions of numpy as installed via conda, or a difference in how a full anaconda vs. miniconda instance sets up environments?  Either way, logic to handle this may be required in setup.py.

**Comment by mattooca** [comment]
Thanks Tim for reporting that!  You're using numpy 2.0, but FUDGE hasn't been updated yet to work with that version.  The simplest solution for now is to downgrade to an older numpy,  e.g. `pip install "numpy<2"` and then try again installing FUDGE.
We will add some documentation about that in the next release, and we expect to support numpy 2.0 later this year.

**Comment by watsot2** [comment]
Hey, thanks for the heads up!  I did as you suggested and it installed just fine.  Thanks!
